/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ToolCondition = IDL.Variant({
  'Fair' : IDL.Null,
  'Good' : IDL.Null,
  'Poor' : IDL.Null,
});
export const ToolStatus = IDL.Variant({
  'Available' : IDL.Null,
  'Issued' : IDL.Null,
});
export const Tool = IDL.Record({
  'id' : IDL.Nat,
  'status' : ToolStatus,
  'purchaseDate' : IDL.Text,
  'availableQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'warrantyExpiry' : IDL.Text,
  'category' : IDL.Text,
  'totalQuantity' : IDL.Nat,
  'location' : IDL.Text,
  'condition' : ToolCondition,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Issue = IDL.Record({
  'id' : IDL.Nat,
  'returnedQuantity' : IDL.Nat,
  'isReturned' : IDL.Bool,
  'issuedDate' : IDL.Text,
  'expectedReturnDate' : IDL.Text,
  'toolId' : IDL.Nat,
  'notes' : IDL.Text,
  'quantity' : IDL.Nat,
  'issuedTo' : IDL.Text,
  'returnDate' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardStats = IDL.Record({
  'totalTools' : IDL.Nat,
  'issuedTools' : IDL.Nat,
  'availableTools' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTool' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        ToolCondition,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
      ],
      [Tool],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changeAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'deleteTool' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getActiveIssues' : IDL.Func([], [IDL.Vec(Issue)], ['query']),
  'getAllTools' : IDL.Func([], [IDL.Vec(Tool)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getTool' : IDL.Func([IDL.Nat], [IDL.Opt(Tool)], ['query']),
  'getToolIssueHistory' : IDL.Func([IDL.Nat], [IDL.Vec(Issue)], ['query']),
  'getToolsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Tool)], ['query']),
  'getToolsByStatus' : IDL.Func([IDL.Bool], [IDL.Vec(Tool)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'issueTool' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Opt(Issue)],
      [],
    ),
  'returnTool' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [IDL.Opt(Issue)], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateTool' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        ToolCondition,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
      ],
      [IDL.Opt(Tool)],
      [],
    ),
  'verifyAdminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ToolCondition = IDL.Variant({
    'Fair' : IDL.Null,
    'Good' : IDL.Null,
    'Poor' : IDL.Null,
  });
  const ToolStatus = IDL.Variant({
    'Available' : IDL.Null,
    'Issued' : IDL.Null,
  });
  const Tool = IDL.Record({
    'id' : IDL.Nat,
    'status' : ToolStatus,
    'purchaseDate' : IDL.Text,
    'availableQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'warrantyExpiry' : IDL.Text,
    'category' : IDL.Text,
    'totalQuantity' : IDL.Nat,
    'location' : IDL.Text,
    'condition' : ToolCondition,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Issue = IDL.Record({
    'id' : IDL.Nat,
    'returnedQuantity' : IDL.Nat,
    'isReturned' : IDL.Bool,
    'issuedDate' : IDL.Text,
    'expectedReturnDate' : IDL.Text,
    'toolId' : IDL.Nat,
    'notes' : IDL.Text,
    'quantity' : IDL.Nat,
    'issuedTo' : IDL.Text,
    'returnDate' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardStats = IDL.Record({
    'totalTools' : IDL.Nat,
    'issuedTools' : IDL.Nat,
    'availableTools' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTool' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ToolCondition,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [Tool],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changeAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'deleteTool' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getActiveIssues' : IDL.Func([], [IDL.Vec(Issue)], ['query']),
    'getAllTools' : IDL.Func([], [IDL.Vec(Tool)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getTool' : IDL.Func([IDL.Nat], [IDL.Opt(Tool)], ['query']),
    'getToolIssueHistory' : IDL.Func([IDL.Nat], [IDL.Vec(Issue)], ['query']),
    'getToolsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Tool)], ['query']),
    'getToolsByStatus' : IDL.Func([IDL.Bool], [IDL.Vec(Tool)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'issueTool' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Opt(Issue)],
        [],
      ),
    'returnTool' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [IDL.Opt(Issue)], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateTool' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          ToolCondition,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [IDL.Opt(Tool)],
        [],
      ),
    'verifyAdminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };