/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'totalTools' : bigint,
  'issuedTools' : bigint,
  'availableTools' : bigint,
}
export interface Issue {
  'id' : bigint,
  'returnedQuantity' : bigint,
  'isReturned' : boolean,
  'issuedDate' : string,
  'expectedReturnDate' : string,
  'toolId' : bigint,
  'notes' : string,
  'quantity' : bigint,
  'issuedTo' : string,
  'returnDate' : string,
}
export interface Tool {
  'id' : bigint,
  'status' : ToolStatus,
  'purchaseDate' : string,
  'availableQuantity' : bigint,
  'name' : string,
  'description' : string,
  'warrantyExpiry' : string,
  'category' : string,
  'totalQuantity' : bigint,
  'location' : string,
  'condition' : ToolCondition,
}
export type ToolCondition = { 'Fair' : null } |
  { 'Good' : null } |
  { 'Poor' : null };
export type ToolStatus = { 'Available' : null } |
  { 'Issued' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTool' : ActorMethod<
    [string, string, ToolCondition, string, string, string, string, bigint],
    Tool
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changeAdminPassword' : ActorMethod<[string, string], boolean>,
  'deleteTool' : ActorMethod<[bigint], boolean>,
  'getActiveIssues' : ActorMethod<[], Array<Issue>>,
  'getAllTools' : ActorMethod<[], Array<Tool>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getTool' : ActorMethod<[bigint], [] | [Tool]>,
  'getToolIssueHistory' : ActorMethod<[bigint], Array<Issue>>,
  'getToolsByCategory' : ActorMethod<[string], Array<Tool>>,
  'getToolsByStatus' : ActorMethod<[boolean], Array<Tool>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'issueTool' : ActorMethod<
    [bigint, string, string, string, string, bigint],
    [] | [Issue]
  >,
  'returnTool' : ActorMethod<[bigint, string, bigint], [] | [Issue]>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateTool' : ActorMethod<
    [
      bigint,
      string,
      string,
      ToolCondition,
      string,
      string,
      string,
      string,
      bigint,
    ],
    [] | [Tool]
  >,
  'verifyAdminLogin' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];