/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Issue {
    id: bigint;
    returnedQuantity: bigint;
    isReturned: boolean;
    issuedDate: string;
    expectedReturnDate: string;
    toolId: bigint;
    notes: string;
    quantity: bigint;
    issuedTo: string;
    returnDate: string;
}
export interface Tool {
    id: bigint;
    status: ToolStatus;
    purchaseDate: string;
    availableQuantity: bigint;
    name: string;
    description: string;
    warrantyExpiry: string;
    category: string;
    totalQuantity: bigint;
    location: string;
    condition: ToolCondition;
}
export interface DashboardStats {
    totalTools: bigint;
    issuedTools: bigint;
    availableTools: bigint;
}
export interface UserProfile {
    name: string;
}
export enum ToolCondition {
    Fair = "Fair",
    Good = "Good",
    Poor = "Poor"
}
export enum ToolStatus {
    Available = "Available",
    Issued = "Issued"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addTool(name: string, category: string, condition: ToolCondition, description: string, location: string, purchaseDate: string, warrantyExpiry: string, totalQuantity: bigint): Promise<Tool>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    changeAdminPassword(currentPassword: string, newPassword: string): Promise<boolean>;
    deleteTool(id: bigint): Promise<boolean>;
    getActiveIssues(): Promise<Array<Issue>>;
    getAllTools(): Promise<Array<Tool>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<DashboardStats>;
    getTool(id: bigint): Promise<Tool | null>;
    getToolIssueHistory(toolId: bigint): Promise<Array<Issue>>;
    getToolsByCategory(category: string): Promise<Array<Tool>>;
    getToolsByStatus(available: boolean): Promise<Array<Tool>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    issueTool(toolId: bigint, issuedTo: string, issuedDate: string, expectedReturnDate: string, notes: string, quantity: bigint): Promise<Issue | null>;
    returnTool(issueId: bigint, returnDate: string, returnQuantity: bigint): Promise<Issue | null>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateTool(id: bigint, name: string, category: string, condition: ToolCondition, description: string, location: string, purchaseDate: string, warrantyExpiry: string, totalQuantity: bigint): Promise<Tool | null>;
    verifyAdminLogin(username: string, password: string): Promise<boolean>;
}
import type { Issue as _Issue, Tool as _Tool, ToolCondition as _ToolCondition, ToolStatus as _ToolStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addTool(arg0: string, arg1: string, arg2: ToolCondition, arg3: string, arg4: string, arg5: string, arg6: string, arg7: bigint): Promise<Tool> {
        if (this.processError) {
            try {
                const result = await this.actor.addTool(arg0, arg1, to_candid_ToolCondition_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7);
                return from_candid_Tool_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTool(arg0, arg1, to_candid_ToolCondition_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7);
            return from_candid_Tool_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async changeAdminPassword(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.changeAdminPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeAdminPassword(arg0, arg1);
            return result;
        }
    }
    async deleteTool(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTool(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTool(arg0);
            return result;
        }
    }
    async getActiveIssues(): Promise<Array<Issue>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveIssues();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveIssues();
            return result;
        }
    }
    async getAllTools(): Promise<Array<Tool>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTools();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTools();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getTool(arg0: bigint): Promise<Tool | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTool(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTool(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getToolIssueHistory(arg0: bigint): Promise<Array<Issue>> {
        if (this.processError) {
            try {
                const result = await this.actor.getToolIssueHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getToolIssueHistory(arg0);
            return result;
        }
    }
    async getToolsByCategory(arg0: string): Promise<Array<Tool>> {
        if (this.processError) {
            try {
                const result = await this.actor.getToolsByCategory(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getToolsByCategory(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getToolsByStatus(arg0: boolean): Promise<Array<Tool>> {
        if (this.processError) {
            try {
                const result = await this.actor.getToolsByStatus(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getToolsByStatus(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async issueTool(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint): Promise<Issue | null> {
        if (this.processError) {
            try {
                const result = await this.actor.issueTool(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.issueTool(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async returnTool(arg0: bigint, arg1: string, arg2: bigint): Promise<Issue | null> {
        if (this.processError) {
            try {
                const result = await this.actor.returnTool(arg0, arg1, arg2);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.returnTool(arg0, arg1, arg2);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateTool(arg0: bigint, arg1: string, arg2: string, arg3: ToolCondition, arg4: string, arg5: string, arg6: string, arg7: string, arg8: bigint): Promise<Tool | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTool(arg0, arg1, arg2, to_candid_ToolCondition_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, arg8);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTool(arg0, arg1, arg2, to_candid_ToolCondition_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, arg8);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyAdminLogin(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAdminLogin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAdminLogin(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ToolCondition_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ToolCondition): ToolCondition {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ToolStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ToolStatus): ToolStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Tool_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tool): Tool {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Tool]): Tool | null {
    return value.length === 0 ? null : from_candid_Tool_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Issue]): Issue | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ToolStatus;
    purchaseDate: string;
    availableQuantity: bigint;
    name: string;
    description: string;
    warrantyExpiry: string;
    category: string;
    totalQuantity: bigint;
    location: string;
    condition: _ToolCondition;
}): {
    id: bigint;
    status: ToolStatus;
    purchaseDate: string;
    availableQuantity: bigint;
    name: string;
    description: string;
    warrantyExpiry: string;
    category: string;
    totalQuantity: bigint;
    location: string;
    condition: ToolCondition;
} {
    return {
        id: value.id,
        status: from_candid_ToolStatus_n5(_uploadFile, _downloadFile, value.status),
        purchaseDate: value.purchaseDate,
        availableQuantity: value.availableQuantity,
        name: value.name,
        description: value.description,
        warrantyExpiry: value.warrantyExpiry,
        category: value.category,
        totalQuantity: value.totalQuantity,
        location: value.location,
        condition: from_candid_ToolCondition_n7(_uploadFile, _downloadFile, value.condition)
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Available: null;
} | {
    Issued: null;
}): ToolStatus {
    return "Available" in value ? ToolStatus.Available : "Issued" in value ? ToolStatus.Issued : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Fair: null;
} | {
    Good: null;
} | {
    Poor: null;
}): ToolCondition {
    return "Fair" in value ? ToolCondition.Fair : "Good" in value ? ToolCondition.Good : "Poor" in value ? ToolCondition.Poor : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Tool>): Array<Tool> {
    return value.map((x)=>from_candid_Tool_n3(_uploadFile, _downloadFile, x));
}
function to_candid_ToolCondition_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ToolCondition): _ToolCondition {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ToolCondition): {
    Fair: null;
} | {
    Good: null;
} | {
    Poor: null;
} {
    return value == ToolCondition.Fair ? {
        Fair: null
    } : value == ToolCondition.Good ? {
        Good: null
    } : value == ToolCondition.Poor ? {
        Poor: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
